/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.DocenteProyectoJpaController;
import controladores.ControladoraDocente;
import controladores.ControladoraProyecto;
import entidad.Docente;
import entidad.Estudiante;
import entidad.Persona;
import entidad.Proyecto;
import entidad.DocenteProyecto;
import entidad.DocenteProyectoPK;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author es982
 */
public class AnteproyectoDocente extends javax.swing.JFrame {

    private ControladoraProyecto controlProyecto = new ControladoraProyecto();
    private ControladoraDocente controlDocente = new ControladoraDocente();
    BancoDeProyectos bp = new BancoDeProyectos();

    private Proyecto proyectoSeleccionado = null;
    private boolean cargandoProyectos = false;

    /**
     * Creates new form AnteproyectoDocente
     */
    public AnteproyectoDocente() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        inicializarFormulario();
        // this.setUndecorated(false);
    }

    private void inicializarFormulario() {
        cargandoProyectos = true;

        cboAnteproyecto.removeAllItems();
        for (Proyecto p : controlProyecto.listarProyectos()) {
            if ("Asignado".equalsIgnoreCase(p.getEstado())) {
                cboAnteproyecto.addItem(p.getNombreProyecto());
            }
        }
        cboAnteproyecto.setSelectedIndex(-1); // No seleccionar por defecto

        cboDocente.removeAllItems();
        cboDocente.addItem("-- Selecciona un docente --");
        for (Docente d : controlDocente.listarDocentes()) {
            String nombreCompleto = d.getIdPersona().getNombre() + " "
                    + d.getIdPersona().getApellidoP() + " "
                    + d.getIdPersona().getApellidoM();
            cboDocente.addItem(nombreCompleto);
        }

        txtAlumnos.setText("");
        txtDescripcion.setText("");

        txtAlumnos.setEditable(false);
        txtDescripcion.setEditable(false);
        cboAnteproyecto.setEditable(false);
        cboDocente.setEditable(false);

        cargandoProyectos = false;
    }

    private Docente buscarDocentePorNombre(String nombreCompleto) {
        for (Docente d : controlDocente.listarDocentes()) {
            String nombre = d.getIdPersona().getNombre() + " "
                    + d.getIdPersona().getApellidoP() + " "
                    + d.getIdPersona().getApellidoM();
            if (nombre.equals(nombreCompleto)) {
                return d;
            }
        }
        return null;
    }

    private void guardarRelacion(Docente docente, Proyecto proyecto, String rol) throws Exception {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("SigerproMVC");
        DocenteProyectoJpaController controlPD = new DocenteProyectoJpaController(emf);

        DocenteProyectoPK pk = new DocenteProyectoPK(proyecto.getIdProyecto(), docente.getNoTarjeta());
        DocenteProyecto existente = controlPD.findDocenteProyecto(pk);

        if (existente != null) {
            throw new Exception("El docente ya está asignado a este proyecto con otro rol: " + existente.getRolDocente());
        }

        DocenteProyecto pd = new DocenteProyecto();
        pd.setDocenteProyectoPK(pk);
        pd.setDocente(docente);
        pd.setProyecto(proyecto);
        pd.setRolDocente(rol);
        controlPD.create(pd);
    }

    private void limpiarFormulario() {
        cboAnteproyecto.setSelectedIndex(-1);
        cboDocente.setSelectedIndex(0);
        txtAlumnos.setText("");
        txtDescripcion.setText("");
        proyectoSeleccionado = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboAnteproyecto = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlumnos = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboDocente = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(161, 161, 161));

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Anteproyecto:");

        cboAnteproyecto.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        cboAnteproyecto.setForeground(new java.awt.Color(153, 153, 153));
        cboAnteproyecto.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(250, 124, 14)))));
        cboAnteproyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAnteproyectoActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 30, 132));
        btnGuardar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtAlumnos.setColumns(20);
        txtAlumnos.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        txtAlumnos.setForeground(new java.awt.Color(153, 153, 153));
        txtAlumnos.setRows(5);
        txtAlumnos.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(250, 124, 14)))));
        jScrollPane1.setViewportView(txtAlumnos);

        jPanel2.setBackground(new java.awt.Color(27, 23, 18));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 124, 14));
        jLabel1.setText("ASIGNAR DOCENTE REVISOR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setBackground(new java.awt.Color(51, 51, 255));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Alumnos:");

        jLabel7.setBackground(new java.awt.Color(51, 51, 255));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Descripción:");

        jLabel8.setBackground(new java.awt.Color(51, 51, 255));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Docente revisor:");

        cboDocente.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        cboDocente.setForeground(new java.awt.Color(153, 153, 153));
        cboDocente.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(250, 124, 14)))));

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(153, 153, 153));
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(250, 124, 14)))));
        jScrollPane2.setViewportView(txtDescripcion);

        btnCancelar.setBackground(new java.awt.Color(255, 0, 51));
        btnCancelar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboAnteproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboAnteproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cboDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnCancelar))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
        if (proyectoSeleccionado == null) {
            JOptionPane.showMessageDialog(null, "Seleccione un anteproyecto primero.");
            return;
        }

        if (!proyectoSeleccionado.getDocenteProyectoCollection().isEmpty()) {
            for (DocenteProyecto dp : proyectoSeleccionado.getDocenteProyectoCollection()) {
                if ("Docente revisor".equalsIgnoreCase(dp.getRolDocente())) {
                    JOptionPane.showMessageDialog(null, "Este anteproyecto ya tiene un docente revisor asignado.");
                    return;
                }
            }
        }

        String docenteNombre = cboDocente.getSelectedIndex() > 0 ? (String) cboDocente.getSelectedItem() : null;

        if (docenteNombre == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un docente.");
            return;
        }

        // Buscar docente
        Docente docente = buscarDocentePorNombre(docenteNombre);

        // Verificar si ya está asignado con otro rol
        for (DocenteProyecto dp : proyectoSeleccionado.getDocenteProyectoCollection()) {
            if (dp.getDocente().getNoTarjeta().equals(docente.getNoTarjeta())) {
                JOptionPane.showMessageDialog(this, "Este docente ya está asignado a este proyecto con otro rol: " + dp.getRolDocente());
                return;
            }
        }

        // Guardar relación
        guardarRelacion(docente, proyectoSeleccionado, "Docente revisor");

        // Actualizar estado
        proyectoSeleccionado.setEstado("En revisión");
        Proyecto actualizado = controlProyecto.buscarProyectoPorId(proyectoSeleccionado.getIdProyecto());
        proyectoSeleccionado.setDocenteProyectoCollection(actualizado.getDocenteProyectoCollection());
        controlProyecto.editarProyecto(proyectoSeleccionado);

        // Refrescar tabla y cerrar
        bp.cargarTablaProyectos();
        JOptionPane.showMessageDialog(null, "Docente asignado correctamente.");
        limpiarFormulario();
        dispose();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error al guardar: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if (!txtDescripcion.getText().isEmpty() || !txtAlumnos.getText().isEmpty()) {
            int opcion = JOptionPane.showConfirmDialog(null,
                    "Hay información cargada. ¿Seguro que desea cancelar?",
                    "Confirmación", JOptionPane.YES_NO_OPTION);
            if (opcion != JOptionPane.YES_OPTION) {
                return;
            }
        }
        limpiarFormulario();
        bp.cargarTablaProyectos();
        dispose(); // cerrar ventana
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cboAnteproyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAnteproyectoActionPerformed
        // TODO add your handling code here:
        if (cargandoProyectos) {
            return;
        }

        String nombreProyecto = (String) cboAnteproyecto.getSelectedItem();
        if (nombreProyecto == null || nombreProyecto.trim().isEmpty()) {
            txtDescripcion.setText("");
            txtAlumnos.setText("");
            proyectoSeleccionado = null;
            return;
        }

        for (Proyecto p : controlProyecto.listarProyectos()) {
            if (p.getNombreProyecto().equals(nombreProyecto)) {
                proyectoSeleccionado = p;
                txtDescripcion.setText(p.getDescripcion());

                StringBuilder alumnos = new StringBuilder();
                for (Estudiante est : p.getEstudianteCollection()) {
                    Persona per = est.getIdPersona();
                    alumnos.append("Nombre: ").append(per.getNombre())
                            .append(" ").append(per.getApellidoP())
                            .append(" ").append(per.getApellidoM())
                            .append(" | No. Control: ").append(est.getNumControl()).append("\n");
                }
                txtAlumnos.setText(alumnos.toString());
                break;
            }
        }
    }//GEN-LAST:event_cboAnteproyectoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnteproyectoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnteproyectoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnteproyectoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnteproyectoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnteproyectoDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboAnteproyecto;
    private javax.swing.JComboBox<String> cboDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAlumnos;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
