/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import entidad.Proyecto;
import controladores.ControladoraProyecto;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane; 
import java.awt.event.ActionListener; 

/**
 *
 * @author Francisco Perez
 */
public class EvaluarProyecto extends javax.swing.JFrame {
    Adaptador a = new Adaptador();
    private Proyecto proyectoAevaluar; 
    private BancoDeProyectos bancoDeProyectos;

    /**
     * Creates new form EvaluarProyecto
     */
    public EvaluarProyecto(Proyecto proyectoAevaluar, BancoDeProyectos bancoDeProyectos) {
    this.setUndecorated(false);
    initComponents();
    this.proyectoAevaluar = proyectoAevaluar;
    this.bancoDeProyectos = bancoDeProyectos;
    configurarVentana();
}


        private void configurarVentana() {
        // Agrupar los JCheckBox para que solo uno pueda ser seleccionado a la vez
        ButtonGroup grupoEvaluacion = new ButtonGroup();
        grupoEvaluacion.add(jCheckAprovado); // Aprobado
        grupoEvaluacion.add(jCheckCorreccion);// Corrección
        grupoEvaluacion.add(jCheckRechazado); // Rechazado

        // Opcional: Deseleccionar todos al inicio
        grupoEvaluacion.clearSelection();

        // Configurar el título de la ventana o algún campo para mostrar el nombre del proyecto
        if (proyectoAevaluar != null) {
            this.setTitle("Evaluar Proyecto: " + proyectoAevaluar.getNombreProyecto());
            // Si tuvieras un JLabel para el nombre del proyecto en esta ventana, podrías usarlo:
            // lblNombreProyecto.setText("Proyecto: " + proyectoAevaluar.getNombreProyecto());
        } else {
            this.setTitle("Evaluar Proyecto");
        }

        // Deshabilitar el botón Guardar inicialmente hasta que una opción sea seleccionada
        jButtonGuardar.setEnabled(false);

        // Añadir listeners a los checkboxes para habilitar el botón Guardar
        ActionListener checkboxListener = e -> jButtonGuardar.setEnabled(jCheckAprovado.isSelected() ||jCheckCorreccion.isSelected() || jCheckRechazado.isSelected());
        jCheckAprovado.addActionListener(checkboxListener);
        jCheckCorreccion.addActionListener(checkboxListener);
        jCheckRechazado.addActionListener(checkboxListener);

        // Añadir ActionListener para el botón Guardar
        jButtonGuardar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jCheckAprovado = new javax.swing.JCheckBox();
        jCheckRechazado = new javax.swing.JCheckBox();
        jButtonCancelar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jCheckCorreccion = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Fondo.setBackground(new java.awt.Color(161, 161, 161));

        jCheckAprovado.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jCheckAprovado.setText("Aprobado");

        jCheckRechazado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jCheckRechazado.setText("Rechazado");

        jButtonCancelar.setBackground(new java.awt.Color(204, 0, 0));
        jButtonCancelar.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseClicked(evt);
            }
        });
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonGuardar.setBackground(new java.awt.Color(255, 51, 0));
        jButtonGuardar.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jCheckCorreccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jCheckCorreccion.setText("Corrección ");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Titulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 51, 0));
        Titulo.setText("¿El proyecto fue aprobado?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Titulo)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(Titulo))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButtonCancelar))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jCheckAprovado)))
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jCheckCorreccion)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckRechazado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGuardar)
                        .addGap(37, 37, 37))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckAprovado)
                    .addComponent(jCheckRechazado)
                    .addComponent(jCheckCorreccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonGuardar))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelarMouseClicked
    a.animarSalida(this);
    dispose();
    }//GEN-LAST:event_jButtonCancelarMouseClicked

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        if (proyectoAevaluar == null) {
            JOptionPane.showMessageDialog(this, "Error: No se ha cargado un proyecto para evaluar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nuevoEstado = "";
            if (jCheckAprovado.isSelected()) {
            nuevoEstado = "Aprobado";
        } else if (jCheckCorreccion.isSelected()){ 
            nuevoEstado = "En corrección";
        } else if (jCheckRechazado.isSelected()) {
            nuevoEstado = "Rechazado";
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione si el proyecto fue Aprobado o Rechazado.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Confirmación antes de guardar
        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea cambiar el estado del proyecto '" + proyectoAevaluar.getNombreProyecto() + "' a '" + nuevoEstado + "'?",
                "Confirmar Evaluación",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                ControladoraProyecto controladora = new ControladoraProyecto();
                proyectoAevaluar.setEstado(nuevoEstado);
                controladora.editarProyecto(proyectoAevaluar); // Suponiendo que tienes un método editarProyecto

                JOptionPane.showMessageDialog(this, "El proyecto ha sido evaluado como: " + nuevoEstado, "Éxito", JOptionPane.INFORMATION_MESSAGE);

                // Refrescar la tabla en BancoDeProyectos si la referencia no es nula
                if (bancoDeProyectos != null) {
                    bancoDeProyectos.cargarTablaProyectos(); // Recargar la tabla principal
                }

                a.animarSalida(this); // Animar salida
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al guardar la evaluación del proyecto: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace(); 
            }
        }    }//GEN-LAST:event_jButtonGuardarActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvaluarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvaluarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvaluarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvaluarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JCheckBox jCheckAprovado;
    private javax.swing.JCheckBox jCheckCorreccion;
    private javax.swing.JCheckBox jCheckRechazado;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
