/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controladores.ControladoraEmpresa;
import java.awt.Color;
import java.awt.Dimension;
import controladores.ControladoraProyecto;
import entidad.Empresa;
import entidad.Proyecto;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Francisco Perez
 */
public class FormularioProyecto extends javax.swing.JFrame {

    Adaptador a = new Adaptador();
    ControladoraProyecto controladoraProyecto;
    BancoDeProyectos bp = new BancoDeProyectos();

    /**
     * Creates new form FormularioProyecto
     */
    public FormularioProyecto() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));

        this.setSize(688, 399);
        this.setMinimumSize(new Dimension(688, 399));
        this.setMaximumSize(new Dimension(688, 399));
        this.setPreferredSize(new Dimension(688, 399));

        this.setResizable(false);
        this.setLocationRelativeTo(null);
        controladoraProyecto = new ControladoraProyecto();
        cargarEmpresasEnComboBox();
        cargarSugeridosEnComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoGris = new javax.swing.JPanel();
        BarraNegra = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        txtFondoNombre1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtFondoNombre3 = new javax.swing.JPanel();
        jComboEmpresas = new javax.swing.JComboBox<>();
        txtFondoNombre4 = new javax.swing.JPanel();
        txtDescripcion = new javax.swing.JTextField();
        txtFondoNombre5 = new javax.swing.JPanel();
        jComboSugeridos = new javax.swing.JComboBox<>();
        lbNombre = new javax.swing.JLabel();
        lbDescripcion = new javax.swing.JLabel();
        lbSugeridos = new javax.swing.JLabel();
        lbEmpresa = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(894, 521));
        setUndecorated(true);

        FondoGris.setBackground(new java.awt.Color(161, 161, 161));

        BarraNegra.setBackground(new java.awt.Color(0, 0, 0));

        txtTitulo.setFont(new java.awt.Font("Tw Cen MT", 1, 52)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 204, 102));
        txtTitulo.setText("Registrar Proyecto");

        javax.swing.GroupLayout BarraNegraLayout = new javax.swing.GroupLayout(BarraNegra);
        BarraNegra.setLayout(BarraNegraLayout);
        BarraNegraLayout.setHorizontalGroup(
            BarraNegraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNegraLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BarraNegraLayout.setVerticalGroup(
            BarraNegraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraNegraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        txtFondoNombre1.setBackground(new java.awt.Color(0, 204, 102));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout txtFondoNombre1Layout = new javax.swing.GroupLayout(txtFondoNombre1);
        txtFondoNombre1.setLayout(txtFondoNombre1Layout);
        txtFondoNombre1Layout.setHorizontalGroup(
            txtFondoNombre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtFondoNombre1Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        txtFondoNombre1Layout.setVerticalGroup(
            txtFondoNombre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtFondoNombre1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtFondoNombre3.setBackground(new java.awt.Color(0, 204, 102));

        jComboEmpresas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout txtFondoNombre3Layout = new javax.swing.GroupLayout(txtFondoNombre3);
        txtFondoNombre3.setLayout(txtFondoNombre3Layout);
        txtFondoNombre3Layout.setHorizontalGroup(
            txtFondoNombre3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtFondoNombre3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jComboEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        txtFondoNombre3Layout.setVerticalGroup(
            txtFondoNombre3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboEmpresas, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        txtFondoNombre4.setBackground(new java.awt.Color(0, 204, 102));

        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout txtFondoNombre4Layout = new javax.swing.GroupLayout(txtFondoNombre4);
        txtFondoNombre4.setLayout(txtFondoNombre4Layout);
        txtFondoNombre4Layout.setHorizontalGroup(
            txtFondoNombre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtFondoNombre4Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        txtFondoNombre4Layout.setVerticalGroup(
            txtFondoNombre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtFondoNombre4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtFondoNombre5.setBackground(new java.awt.Color(0, 204, 102));

        jComboSugeridos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        javax.swing.GroupLayout txtFondoNombre5Layout = new javax.swing.GroupLayout(txtFondoNombre5);
        txtFondoNombre5.setLayout(txtFondoNombre5Layout);
        txtFondoNombre5Layout.setHorizontalGroup(
            txtFondoNombre5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtFondoNombre5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jComboSugeridos, 0, 231, Short.MAX_VALUE)
                .addContainerGap())
        );
        txtFondoNombre5Layout.setVerticalGroup(
            txtFondoNombre5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboSugeridos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        lbNombre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbNombre.setText("Nombre");

        lbDescripcion.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbDescripcion.setText("Descripción");

        lbSugeridos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbSugeridos.setText("Numero de residentes sugeridos");

        lbEmpresa.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbEmpresa.setText("Empresa");

        btnCancelar.setBackground(new java.awt.Color(255, 0, 51));
        btnCancelar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(0, 204, 102));
        btnRegistrar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoGrisLayout = new javax.swing.GroupLayout(FondoGris);
        FondoGris.setLayout(FondoGrisLayout);
        FondoGrisLayout.setHorizontalGroup(
            FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraNegra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoGrisLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FondoGrisLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoGrisLayout.createSequentialGroup()
                        .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFondoNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombre)
                            .addComponent(lbSugeridos)
                            .addComponent(txtFondoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFondoNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDescripcion)
                            .addComponent(lbEmpresa)
                            .addComponent(txtFondoNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(122, 122, 122))
        );
        FondoGrisLayout.setVerticalGroup(
            FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoGrisLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BarraNegra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(lbDescripcion))
                .addGap(12, 12, 12)
                .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFondoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFondoNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSugeridos)
                    .addComponent(lbEmpresa))
                .addGap(26, 26, 26)
                .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFondoNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFondoNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoGris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoGris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        bp.cargarTablaProyectos();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        a.animarSalida(this);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String nombreProyecto = txtNombre.getText();
        String descripcion = txtDescripcion.getText();
        String numAlumnosSugeridosStr = (String) jComboSugeridos.getSelectedItem();
        String nombreEmpresaSeleccionada = (String) jComboEmpresas.getSelectedItem();

        String nombreEmpresa = "";
        Empresa empresaSeleccionada = null;
        final int MAX_NOMBRE_LENGTH = 254; 
        final int MAX_DESCRIPCION_LENGTH = 254; 
        
        if (nombreProyecto.length() > MAX_NOMBRE_LENGTH) {
        JOptionPane.showMessageDialog(this, "El nombre del proyecto no puede exceder los " + MAX_NOMBRE_LENGTH + " caracteres.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
        return;
    }

if (descripcion.length() > MAX_DESCRIPCION_LENGTH) {
    JOptionPane.showMessageDialog(this, "La descripción no puede exceder los " + MAX_DESCRIPCION_LENGTH + " caracteres.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
    return;
}


        if (descripcion.length() > MAX_DESCRIPCION_LENGTH) {
        JOptionPane.showMessageDialog(this, "La descripción no puede exceder los " + MAX_DESCRIPCION_LENGTH + " caracteres.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
        txtDescripcion.setText("");
        txtNombre.setText("");
        return;
        }
        


        if (nombreEmpresaSeleccionada != null) {
            if (nombreEmpresaSeleccionada.equals("No hay empresas registradas") && !jComboEmpresas.isEnabled()) {
                JOptionPane.showMessageDialog(this, "No hay empresas disponibles para seleccionar.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Buscar empresa usando el controlador
            ControladoraEmpresa controlEmpresa = new ControladoraEmpresa();
            empresaSeleccionada = controlEmpresa.buscarEmpresaPorNombre(nombreEmpresaSeleccionada);
            System.out.println(empresaSeleccionada.getNombreEmpresa());

            if (empresaSeleccionada != null) {
                nombreEmpresa = empresaSeleccionada.getNombreEmpresa();
            } else {
                JOptionPane.showMessageDialog(this, "La empresa seleccionada no fue encontrada. Por favor, recargue la lista.", "Error de Datos", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una empresa.", "Error de Selección", JOptionPane.WARNING_MESSAGE);
            return;
        }

// Estado y documento por defecto
        String estadoProyecto = "Sin Asignar";
        String urlDocumento = "N/A";

        try {
            // Validar campos obligatorios
            if (nombreProyecto.isEmpty() || descripcion.isEmpty() || numAlumnosSugeridosStr == null
                    || numAlumnosSugeridosStr.isEmpty() || nombreEmpresa.isEmpty() ) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error de Validación", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Integer numAlumnS = Integer.parseInt(numAlumnosSugeridosStr);
            Date fechaActual = new Date();

            Proyecto nuevoProyecto = new Proyecto();
            nuevoProyecto.setNombreProyecto(nombreProyecto);
            nuevoProyecto.setDescripcion(descripcion);
            nuevoProyecto.setEstado(estadoProyecto);
            nuevoProyecto.setUrlDocumento(urlDocumento);
            nuevoProyecto.setNumAlumnosSug(numAlumnS);
            nuevoProyecto.setFechaRegistro(fechaActual);
            nuevoProyecto.setIdEmpresa(empresaSeleccionada);
            controladoraProyecto.guardarProyecto(nuevoProyecto);

            JOptionPane.showMessageDialog(this, "Proyecto registrado exitosamente.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
            cargarEmpresasEnComboBox();
            bp.cargarTablaProyectos();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El número de alumnos sugeridos debe ser un número entero válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado al registrar el proyecto: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
    String textoActual = txtNombre.getText();  // ← Aquí estaba el error, usabas txtDescripcion
    final int MAX_LENGTH = 254;

    // Permitir retroceso y suprimir
    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar() == KeyEvent.VK_DELETE) {
        return;
    }

    // Permitir letras y espacios
    if (!Character.isLetter(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
        evt.consume();
        return;
    }

    // Evitar escribir más de 254 caracteres
    if (textoActual.length() >= MAX_LENGTH) {
        evt.consume();
    }

    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
    String textoActual = txtDescripcion.getText();
    final int MAX_LENGTH = 254;

    // Permitir retroceso y suprimir
    if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar() == KeyEvent.VK_DELETE) {
        return;
    }

    // Permitir letras y espacios
    if (!Character.isLetter(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar())) {
        evt.consume();
        return;
    }

    // Evitar escribir más de 254 caracteres
    if (textoActual.length() >= MAX_LENGTH) {
        evt.consume();}

    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void cargarEmpresasEnComboBox() {
        List<Empresa> empresas = controladoraProyecto.obtenerTodasLasEmpresas();

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        if (empresas != null && !empresas.isEmpty()) {
            for (Empresa empresa : empresas) {
                model.addElement(empresa.getNombreEmpresa());
            }
            jComboEmpresas.setModel(model);
            jComboEmpresas.setEnabled(true);

            if (jComboEmpresas.getItemCount() > 0) {
                jComboEmpresas.setSelectedIndex(0);
            }
        } else {
            DefaultComboBoxModel<String> emptyModel = new DefaultComboBoxModel<>();
            emptyModel.addElement("No hay empresas registradas");

            jComboEmpresas.setModel(emptyModel);
            jComboEmpresas.setEnabled(false);
        }

    }

    private void cargarSugeridosEnComboBox() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (int i = 1; i <= 4; i++) {
            model.addElement(String.valueOf(i));
        }
        jComboSugeridos.setModel(model);
        jComboSugeridos.setSelectedIndex(0);
    }

    private void limpiarCampos() {
        txtNombre.setText("");
        txtDescripcion.setText("");
        if (jComboSugeridos.getItemCount() > 0) {
            jComboSugeridos.setSelectedIndex(0);
        }
        if (jComboEmpresas.getItemCount() > 0) {
            jComboEmpresas.setSelectedIndex(0);
        }
       // txtNumeroContacto.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraNegra;
    private javax.swing.JPanel FondoGris;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> jComboEmpresas;
    private javax.swing.JComboBox<String> jComboSugeridos;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbEmpresa;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbSugeridos;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JPanel txtFondoNombre1;
    private javax.swing.JPanel txtFondoNombre3;
    private javax.swing.JPanel txtFondoNombre4;
    private javax.swing.JPanel txtFondoNombre5;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
