/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controladores.ControladoraPersona;
import controladores.ControladoraUsuario;
import entidad.Persona;
import entidad.Usuario;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.ArrayList;
import java.util.Optional;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import servicio.ControladorEmails;
import servicio.EncriptarPassword;

/**
 *
 * @author jc389
 */
public class IniciarSesion extends javax.swing.JFrame {

    public String textUser = "Ingrese su usuario o correo electrónico:";
    public String textPass = "Ingrese su contraseña:";
    ControladorEmails email = new ControladorEmails();
    EncriptarPassword encrip=new EncriptarPassword();
    String codigo = "";
    //String codigo = email.getCodigo();
    int contador;
    String variableUsuario;
    public final ControladoraUsuario controlU = new ControladoraUsuario();

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {

        initComponents();
        lblVer1.setVisible(false);
        this.setLocationRelativeTo(null);
        ajustar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicio = new javax.swing.JPanel();
        iniciaSesion = new javax.swing.JLabel();
        frase2 = new javax.swing.JLabel();
        frase_derecha = new javax.swing.JLabel();
        frase1 = new javax.swing.JLabel();
        bienvenido = new javax.swing.JLabel();
        logoITO = new javax.swing.JLabel();
        SIGERPRO = new javax.swing.JLabel();
        iconoPassword = new javax.swing.JLabel();
        iconoUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        fondoOscuro = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        lblVer1 = new javax.swing.JLabel();
        lblVer = new javax.swing.JLabel();
        lblPassword1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblRecuperar = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        fondoClaro = new javax.swing.JLabel();
        panelRecuperar = new javax.swing.JPanel();
        btnEnviar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        FONDO1 = new javax.swing.JLabel();
        panelRecuperar2 = new javax.swing.JPanel();
        btnComprobar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtComprobar = new javax.swing.JTextField();
        lblIncorrecto = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();
        panelRecuperar3 = new javax.swing.JPanel();
        btnComprobar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ps2Contraseña = new javax.swing.JPasswordField();
        psContraseña = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        lblMostrar = new javax.swing.JLabel();
        lblOcultar = new javax.swing.JLabel();
        FONDO2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(687, 410));
        setSize(new java.awt.Dimension(1009, 540));
        getContentPane().setLayout(new java.awt.CardLayout());

        panelInicio.setPreferredSize(new java.awt.Dimension(1009, 539));
        panelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciaSesion.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        iniciaSesion.setForeground(new java.awt.Color(0, 0, 0));
        iniciaSesion.setText("INICIAR SESIÓN");
        panelInicio.add(iniciaSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 350, 50));

        frase2.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        frase2.setForeground(new java.awt.Color(255, 255, 255));
        frase2.setText("al servicio de tu formación.\"");
        panelInicio.add(frase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 310, 50));

        frase_derecha.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        frase_derecha.setForeground(new java.awt.Color(0, 0, 0));
        frase_derecha.setText("Accede al sistema para las funciones de administrador");
        panelInicio.add(frase_derecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 370, 40));

        frase1.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        frase1.setForeground(new java.awt.Color(255, 255, 255));
        frase1.setText("\"SIGERPRO: Control y seguimiento ");
        panelInicio.add(frase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 390, 80));

        bienvenido.setFont(new java.awt.Font("Georgia", 0, 35)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(234, 114, 9));
        bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bienvenido.setText("Bienvenido a ");
        panelInicio.add(bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 360, 60));

        logoITO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ITO.png"))); // NOI18N
        panelInicio.add(logoITO, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 160, 160));

        SIGERPRO.setFont(new java.awt.Font("Georgia", 0, 70)); // NOI18N
        SIGERPRO.setForeground(new java.awt.Color(234, 114, 9));
        SIGERPRO.setText("SIGERPRO");
        panelInicio.add(SIGERPRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 360, 100));

        iconoPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/candado(inicio sesion).png"))); // NOI18N
        panelInicio.add(iconoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 50, 50));

        iconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/persona (inicio sesion).png"))); // NOI18N
        panelInicio.add(iconoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 50, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);
        panelInicio.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 340, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOpaque(true);
        panelInicio.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 340, -1));

        fondoOscuro.setBackground(new java.awt.Color(32, 31, 29));
        fondoOscuro.setOpaque(true);
        panelInicio.add(fondoOscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 540));

        btnIniciar.setBackground(new java.awt.Color(244, 127, 2));
        btnIniciar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("INGRESAR");
        btnIniciar.setBorder(null);
        btnIniciar.setOpaque(true);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        panelInicio.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 220, 50));

        lblVer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVer1MouseClicked(evt);
            }
        });
        panelInicio.add(lblVer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 300, 30, 30));

        lblVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVerMouseClicked(evt);
            }
        });
        panelInicio.add(lblVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 300, 30, 30));

        lblPassword1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        lblPassword1.setForeground(new java.awt.Color(154, 49, 7));
        lblPassword1.setText("© 2025 SIGERPRO. Sistema de Gestión de Residencias Profesionales. Todos los derechos reservados.");
        panelInicio.add(lblPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 570, -1));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.setFocusable(false);
        txtPassword.setOpaque(true);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPasswordMouseEntered(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        panelInicio.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 340, 30));

        lblRecuperar.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        lblRecuperar.setForeground(new java.awt.Color(231, 143, 2));
        lblRecuperar.setText("¿Contraseña olvidada? Reestablecer ahora mismo");
        lblRecuperar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRecuperarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRecuperarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRecuperarMouseExited(evt);
            }
        });
        panelInicio.add(lblRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 300, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario.setText("Ingrese su usuario o correo electrónico:");
        txtUsuario.setBorder(null);
        txtUsuario.setFocusable(false);
        txtUsuario.setOpaque(true);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseExited(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        panelInicio.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 340, 30));

        fondoClaro.setBackground(new java.awt.Color(255, 255, 255));
        fondoClaro.setOpaque(true);
        panelInicio.add(fondoClaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 580, 540));

        getContentPane().add(panelInicio, "card20");

        panelRecuperar.setPreferredSize(new java.awt.Dimension(640, 400));
        panelRecuperar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnviar.setBackground(new java.awt.Color(0, 0, 255));
        btnEnviar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.setBorder(null);
        btnEnviar.setOpaque(true);
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarMouseClicked(evt);
            }
        });
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        panelRecuperar.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 400, 30));

        btnCancelar.setBackground(new java.awt.Color(153, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.setOpaque(true);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelRecuperar.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 400, 30));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Restablecer contraseña");
        panelRecuperar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Introduce tu usuario o correo para recibir el código de recuperación.");
        panelRecuperar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 255), null, null, new java.awt.Color(0, 204, 204)));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        panelRecuperar.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 400, 40));

        FONDO1.setBackground(new java.awt.Color(255, 255, 255));
        FONDO1.setOpaque(true);
        panelRecuperar.add(FONDO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 410));

        getContentPane().add(panelRecuperar, "card3");

        panelRecuperar2.setPreferredSize(new java.awt.Dimension(640, 400));
        panelRecuperar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComprobar.setBackground(new java.awt.Color(0, 0, 255));
        btnComprobar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnComprobar.setForeground(new java.awt.Color(255, 255, 255));
        btnComprobar.setText("Comprobar");
        btnComprobar.setBorder(null);
        btnComprobar.setOpaque(true);
        btnComprobar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprobarMouseClicked(evt);
            }
        });
        btnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarActionPerformed(evt);
            }
        });
        panelRecuperar2.add(btnComprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 400, 30));

        btnRegresar.setBackground(new java.awt.Color(153, 153, 153));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.setOpaque(true);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        panelRecuperar2.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 400, 30));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Restablecer contraseña");
        panelRecuperar2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Introduce el código que fue enviado al correo ");
        panelRecuperar2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        txtComprobar.setBackground(new java.awt.Color(255, 255, 255));
        txtComprobar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 255), null, null, new java.awt.Color(0, 204, 204)));
        txtComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComprobarActionPerformed(evt);
            }
        });
        panelRecuperar2.add(txtComprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 400, 40));

        lblIncorrecto.setForeground(new java.awt.Color(255, 0, 0));
        lblIncorrecto.setText("Codigo incorrecto.");
        panelRecuperar2.add(lblIncorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 120, -1));

        FONDO.setBackground(new java.awt.Color(255, 255, 255));
        FONDO.setOpaque(true);
        panelRecuperar2.add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 410));

        getContentPane().add(panelRecuperar2, "card3");

        panelRecuperar3.setPreferredSize(new java.awt.Dimension(640, 400));
        panelRecuperar3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComprobar1.setBackground(new java.awt.Color(0, 0, 255));
        btnComprobar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnComprobar1.setForeground(new java.awt.Color(255, 255, 255));
        btnComprobar1.setText("Aceptar");
        btnComprobar1.setBorder(null);
        btnComprobar1.setOpaque(true);
        btnComprobar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprobar1MouseClicked(evt);
            }
        });
        btnComprobar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobar1ActionPerformed(evt);
            }
        });
        panelRecuperar3.add(btnComprobar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 130, 30));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Reestablecer contraseña");
        panelRecuperar3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Confirme su nueva contraseña:");
        panelRecuperar3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        ps2Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps2ContraseñaActionPerformed(evt);
            }
        });
        panelRecuperar3.add(ps2Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 290, 40));
        panelRecuperar3.add(psContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 290, 40));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Ingrese su nueva contraseña:");
        panelRecuperar3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        lblMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eyeMostrar.jpeg"))); // NOI18N
        lblMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMostrarMouseClicked(evt);
            }
        });
        panelRecuperar3.add(lblMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 40, 40));

        lblOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/211739_eye_icon.png"))); // NOI18N
        lblOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOcultarMouseClicked(evt);
            }
        });
        panelRecuperar3.add(lblOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 40, 40));

        FONDO2.setBackground(new java.awt.Color(255, 255, 255));
        FONDO2.setOpaque(true);
        panelRecuperar3.add(FONDO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 420));

        getContentPane().add(panelRecuperar3, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        if (contador == 5) {
            JOptionPane.showMessageDialog(null, "Demasiados intentos, espere 10 segundos para volver a intentar");
            btnIniciar.setEnabled(false); // desactiva el botón
            contador = 0; // reinicia el contador

            // Timer que lo reactivará en 10 segundos (10000 ms)
            Timer timer = new Timer(10000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btnIniciar.setEnabled(true);
                    ((Timer) e.getSource()).stop(); // detiene el timer
                }
            });
            timer.setRepeats(false); // para que se ejecute una sola vez
            timer.start();

        } else {
            iniciarSesion();
            
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        txtPassword.requestFocusInWindow();
        txtPassword.setFocusable(true);
// TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        if (txtUsuario.getText().equals(textUser)) {
            txtUsuario.setText("");
        }
        txtUsuario.setText(txtUsuario.getText());
        comprobarP();


    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void txtUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseEntered
        // TODO add your handling code here:
        txtUsuario.setFocusable(true);
    }//GEN-LAST:event_txtUsuarioMouseEntered

    private void txtUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseExited

// TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioMouseExited

    private void lblRecuperarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarMouseEntered
        // TODO add your handling code here:
        lblRecuperar.setForeground(new Color(51, 102, 255));
    }//GEN-LAST:event_lblRecuperarMouseEntered

    private void lblRecuperarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarMouseExited
        // TODO add your handling code here:
        lblRecuperar.setForeground(new Color(231, 143, 2));
    }//GEN-LAST:event_lblRecuperarMouseExited

    private void lblRecuperarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarMouseClicked
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        panelRecuperar.setSize(687, 410);
        this.setSize(687, 410);

        panelRecuperar.setVisible(true);
        panelInicio.setVisible(false);


    }//GEN-LAST:event_lblRecuperarMouseClicked

    private void btnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarActionPerformed
        // TODO add your handling code here:
        System.out.println(codigo);
        if (comprobarCodigo()) {
            panelRecuperar2.setVisible(false);
            panelRecuperar3.setVisible(true);
            lblIncorrecto.setVisible(false);
            lblOcultar.setVisible(false);

        } else {
            lblIncorrecto.setVisible(true);
        }


    }//GEN-LAST:event_btnComprobarActionPerformed

    public boolean comprobarCodigo() {
        String aux = txtComprobar.getText();
        if (aux.equals(codigo)) {
            System.out.println("Codigo correcto");
            return true;

        } else {
            return false;
        }

    }

    private void actualizarContraseña() {        //Carga los archivos de la base de datos en un arrayList y luego comprueba
        String correo = txtCorreo.getText();
        String pw = new String(psContraseña.getPassword());
        System.out.println("pw");
        String contraEncriptada=encrip.encriptarPassword(pw);
        ArrayList<Usuario> listaUsuario = controlU.listarUsuarios();
        if (!pw.isEmpty()) {
            for (Usuario u : listaUsuario) {
                if (u.getCorreo().equals(correo) || u.getNombreUsuario().equals(correo)) {
                    //JOptionPane.showMessageDialog(null, "Usuario no enontrado");
                    Integer id = u.getIdUsuario();
                    String nU = u.getNombreUsuario();
                    String cU = u.getCorreo();
                    Usuario u1 = new Usuario();
                    u1.setIdUsuario(id);
                    u1.setNombreUsuario(nU);
                    u1.setContraseniaHash(contraEncriptada);
                    u1.setCorreo(cU);
                    controlU.editarUsuario(u1);
                    JOptionPane.showMessageDialog(null, "Contraseña editada");

                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Llena los campos por favor");
        }
    }

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComprobarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComprobarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if (!txtCorreo.getText().isEmpty()) {
            String correo = txtCorreo.getText();

            String cCorreo = controlU.buscarCorreoOUser(correo);
            if (!cCorreo.equals("")) {
                email.crearCorreoCodigoRecuperacion(cCorreo);// TODO add your handling code here:
                email.enviarEmail();
                codigo = email.codigo;
                panelRecuperar.setVisible(false);
                panelRecuperar2.setVisible(true);
                lblIncorrecto.setVisible(false);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Ingresa el correo primero");
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        panelRecuperar.setVisible(false);
        this.setSize(1009, 570);

        panelInicio.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseClicked
        panelRecuperar.setVisible(false);
        panelRecuperar2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarMouseClicked

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        panelRecuperar2.setVisible(false);
        panelRecuperar.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnComprobar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobar1ActionPerformed
        actualizarContraseña();
        panelRecuperar3.setVisible(false);
        panelInicio.setVisible(true);// TODO add your handling code here:
        this.setSize(1031, 560);
    }//GEN-LAST:event_btnComprobar1ActionPerformed

    private void btnComprobar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprobar1MouseClicked
        panelRecuperar3.setVisible(false);
        panelInicio.setVisible(true);// TODO add your handling code here:
        panelInicio.setSize(1012, 540);
    }//GEN-LAST:event_btnComprobar1MouseClicked

    private void ps2ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps2ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ps2ContraseñaActionPerformed

    private void btnComprobarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprobarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprobarMouseClicked

    private void lblOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOcultarMouseClicked
        lblOcultar.setVisible(false);
        lblMostrar.setVisible(true);
        psContraseña.setEchoChar('*');
        ps2Contraseña.setEchoChar('*');
    }//GEN-LAST:event_lblOcultarMouseClicked

    private void lblMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMostrarMouseClicked
        lblOcultar.setVisible(true);
        lblMostrar.setVisible(false);
        psContraseña.setEchoChar((char) 0);
        ps2Contraseña.setEchoChar((char) 0);
    }//GEN-LAST:event_lblMostrarMouseClicked

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if (txtUsuario.getText().equals(textUser)) {
            txtUsuario.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if (txtUsuario.getText().trim().isEmpty()) {
            txtUsuario.setText(textUser);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
        btnIniciar.doClick();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        String texto = String.valueOf(txtPassword.getPassword());
        if (texto.equals(textPass)) {
            txtPassword.setText("");
            txtPassword.setEchoChar('●'); // Activa modo oculto
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        String texto = String.valueOf(txtPassword.getPassword());
        if (texto.trim().isEmpty()) {
            txtPassword.setText(textPass);
            txtPassword.setFont(new Font("Georgia", Font.PLAIN, 18));
            txtPassword.setEchoChar((char) 0); // Mostrar texto plano
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseEntered
        txtPassword.setFocusable(true);        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordMouseEntered

    private void lblVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVerMouseClicked
        // TODO add your handling code here:
        lblVer1.setVisible(true);
        lblVer.setVisible(false);
        txtPassword.setEchoChar((char) 0);
        txtPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_lblVerMouseClicked

    private void lblVer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVer1MouseClicked
        // TODO add your handling code here:
        lblVer1.setVisible(false);
        lblVer.setVisible(true);
        txtPassword.setEchoChar('*');
        txtPassword.setEchoChar('*');
    }//GEN-LAST:event_lblVer1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    private void comprobarU() {
        if (txtUsuario.getText().trim().isEmpty()) {
            txtUsuario.setText(textUser);
        }
    }

    private void comprobarP() {
        if (txtPassword.getText().equals("")) {
            txtPassword.setText(textPass);
        }
        txtPassword.setText(txtPassword.getText());
    }

    private void ajustarImagenALabel(JLabel label, String rutaRelativa) {
        URL recurso = getClass().getResource("/" + rutaRelativa);

        if (recurso != null) {
            ImageIcon icono = new ImageIcon(recurso);
            Image imagenOriginal = icono.getImage();
            Image imagenEscalada = imagenOriginal.getScaledInstance(
                    label.getWidth(),
                    label.getHeight(),
                    Image.SCALE_SMOOTH
            );
            label.setIcon(new ImageIcon(imagenEscalada));
        } else {
            System.err.println("❌ No se encontró la imagen: /" + rutaRelativa);
        }
    }

    public void ajustar() {
        ajustarImagenALabel(logoITO, "Imagenes/ITO.png");
        ajustarImagenALabel(iconoUsuario, "Imagenes/persona (inicio sesion).png");
        ajustarImagenALabel(iconoPassword, "Imagenes/candado(inicio sesion).png");
        ajustarImagenALabel(lblVer, "Imagenes/eye.png");
        ajustarImagenALabel(lblVer1, "Imagenes/eyeO.png");

    }
    //Inicia sesion

    private String verificarCredenciales(String user, String contra, ArrayList<Usuario> listaUsuario) {
        Optional<Usuario> foundUser = listaUsuario.stream()
                .filter(u -> u.getNombreUsuario().equals(user) || u.getCorreo().equals(user))
                .findFirst();
   if (foundUser.isPresent()) {
        // Solo verificamos la contraseña si el usuario fue encontrado
        boolean auxPassword = encrip.verificarPassword(contra, foundUser.get().getContraseniaHash());
        if (auxPassword) {
            return "Acceso verificado";
        } else {
            return "Contraseña incorrecta";
           
        }
    } else {
        return "Usuario incorrecto";
    }
}

    //Carga los archivos de la base de datos en un arrayList y luego comprueba
    private void listarUsuarios(String user, String contra) {
        ArrayList<Usuario> listaUsuario = controlU.listarUsuarios();

        if (listaUsuario == null || listaUsuario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se encontró ningún Usuario Registrado", "ERROR USUARIO", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String status = verificarCredenciales(user, contra, listaUsuario);

        switch (status) {
            case "Acceso verificado":
                JOptionPane.showMessageDialog(null, "Acceso verificado");
                variableUsuario=txtUsuario.getText();
                PanelPrincipal principal = new PanelPrincipal();
                principal.contrasena=txtPassword.getText();
                principal.setExtendedState(JFrame.MAXIMIZED_BOTH);
                principal.setVisible(true);
                this.dispose(); // Close the login frame
                break;
            case "Usuario incorrecto":
                JOptionPane.showMessageDialog(null, "Usuario incorrecto");
                txtUsuario.setText(""); // Clear username field
                comprobarU(); // Call your method to handle UI for incorrect username
                break;
            case "Contraseña incorrecta":
                JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
                txtPassword.setText(""); // Clear password field
                comprobarP(); // Call your method to handle UI for incorrect password
                break;
            default:
                // This case should ideally not be reached
                JOptionPane.showMessageDialog(null, "Error desconocido en la verificación de credenciales.");
                break;
        }
    }

    //Inicia sesion
    private void iniciarSesion() {
        if (txtUsuario.getText().isEmpty() || txtUsuario.getText().equals(textUser)) { // <--- MODIFICA ESTA LÍNEA
            JOptionPane.showMessageDialog(null, "Ingresa tu usuario o correo electrónico");
        } else if (txtPassword.getText().isEmpty() || txtPassword.getPassword().equals(textPass)) { // <--- MODIFICA ESTA LÍNEA
            JOptionPane.showMessageDialog(null, "Ingresa tu contraseña");
        } else {
            String usuario = txtUsuario.getText();
            String contra = txtPassword.getText(); // <--- MANTIENE ESTA LÍNEA (NO USAR getPassword())
            listarUsuarios(usuario, contra);
        }
    }

    //Carga los archivos de la base de datos en un arrayList y luego comprueba

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JLabel FONDO1;
    private javax.swing.JLabel FONDO2;
    private javax.swing.JLabel SIGERPRO;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnComprobar;
    private javax.swing.JButton btnComprobar1;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel fondoClaro;
    private javax.swing.JLabel fondoOscuro;
    private javax.swing.JLabel frase1;
    private javax.swing.JLabel frase2;
    private javax.swing.JLabel frase_derecha;
    private javax.swing.JLabel iconoPassword;
    private javax.swing.JLabel iconoUsuario;
    private javax.swing.JLabel iniciaSesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblIncorrecto;
    private javax.swing.JLabel lblMostrar;
    private javax.swing.JLabel lblOcultar;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblRecuperar;
    private javax.swing.JLabel lblVer;
    private javax.swing.JLabel lblVer1;
    private javax.swing.JLabel logoITO;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelRecuperar;
    private javax.swing.JPanel panelRecuperar2;
    private javax.swing.JPanel panelRecuperar3;
    private javax.swing.JPasswordField ps2Contraseña;
    private javax.swing.JPasswordField psContraseña;
    private javax.swing.JTextField txtComprobar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
