/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.DocenteProyectoJpaController;
import controladores.ControladoraDocente;
import controladores.ControladoraProyecto;
import entidad.Docente;
import entidad.Estudiante;
import entidad.Persona;
import entidad.Proyecto;
import entidad.DocenteProyecto;
import entidad.DocenteProyectoPK;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author iigna
 */
public class ProyectoRevAse extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProyectoRevAse.class.getName());

    ControladoraProyecto controlProyecto = new ControladoraProyecto();
    ControladoraDocente controlDocente = new ControladoraDocente();

    private Proyecto proyectoSeleccionado = null;
    private boolean cargandoProyectos = false;

    /**
     * Creates new form ProyectoRevAse
     */
    public ProyectoRevAse() {
        this.setUndecorated(false);
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        inicializarFormulario();
    }

    private void inicializarFormulario() {
        cargandoProyectos = true; // ← Evita que se dispare el listener al cargar

        cboProyecto.removeAllItems();
        for (Proyecto p : controlProyecto.listarProyectos()) {
            if ("Aprobado".equalsIgnoreCase(p.getEstado())) {
                cboProyecto.addItem(p.getNombreProyecto());
            }
        }
        cboProyecto.setSelectedIndex(-1); // Sin selección inicial

        cboAsesor.removeAllItems();
        cboRevisor1.removeAllItems();
        cboRevisor2.removeAllItems();

        cboAsesor.addItem("-- Selecciona un docente --");
        cboRevisor1.addItem("-- Selecciona un docente --");
        cboRevisor2.addItem("-- Selecciona un docente --");

        for (Docente d : controlDocente.listarDocentes()) {
            String nombreCompleto = d.getIdPersona().getNombre() + " "
                    + d.getIdPersona().getApellidoP() + " "
                    + d.getIdPersona().getApellidoM();
            cboAsesor.addItem(nombreCompleto);
            cboRevisor1.addItem(nombreCompleto);
            cboRevisor2.addItem(nombreCompleto);
        }

        txtAlumnos.setText("");
        txtDescripcion.setText("");

        txtAlumnos.setEditable(false);
        txtDescripcion.setEditable(false);
        cboProyecto.setEditable(false);
        cboAsesor.setEditable(false);
        cboRevisor1.setEditable(false);
        cboRevisor2.setEditable(false);

        cargandoProyectos = false; // ← Reactiva el listener
    }

    private boolean docenteYaAsignado(Proyecto proyecto, Docente docente) {
    for (DocenteProyecto dp : proyecto.getDocenteProyectoCollection()) {
        if (dp.getDocente().getNoTarjeta().equals(docente.getNoTarjeta())) {
            return true;
        }
    }
    return false;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboProyecto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlumnos = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        cboAsesor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cboRevisor1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cboRevisor2 = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(161, 161, 161));

        jPanel2.setBackground(new java.awt.Color(27, 23, 18));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 124, 14));
        jLabel2.setText("ASIGNAR ASESOR Y REVISOR(ES)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        cboProyecto.setBackground(new java.awt.Color(255, 255, 255));
        cboProyecto.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        cboProyecto.setForeground(new java.awt.Color(153, 153, 153));
        cboProyecto.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(250, 124, 14)))));
        cboProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProyectoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Proyecto:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Descripción:");

        txtAlumnos.setBackground(new java.awt.Color(255, 255, 255));
        txtAlumnos.setColumns(20);
        txtAlumnos.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        txtAlumnos.setForeground(new java.awt.Color(153, 153, 153));
        txtAlumnos.setRows(5);
        txtAlumnos.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(250, 124, 14)))));
        jScrollPane1.setViewportView(txtAlumnos);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Alumnos:");

        txtDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(153, 153, 153));
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(250, 124, 14)))));
        jScrollPane2.setViewportView(txtDescripcion);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Asesor:");

        cboAsesor.setBackground(new java.awt.Color(255, 255, 255));
        cboAsesor.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        cboAsesor.setForeground(new java.awt.Color(153, 153, 153));
        cboAsesor.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(250, 124, 14)))));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Primer revisor:");

        cboRevisor1.setBackground(new java.awt.Color(255, 255, 255));
        cboRevisor1.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        cboRevisor1.setForeground(new java.awt.Color(153, 153, 153));
        cboRevisor1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(250, 124, 14)))));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Segundo revisor:");

        cboRevisor2.setBackground(new java.awt.Color(255, 255, 255));
        cboRevisor2.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        cboRevisor2.setForeground(new java.awt.Color(153, 153, 153));
        cboRevisor2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(250, 124, 14)))));

        btnGuardar.setBackground(new java.awt.Color(0, 30, 132));
        btnGuardar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 0, 51));
        btnCancelar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1)
                        .addComponent(cboProyecto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(cboRevisor1, 0, 420, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addComponent(cboRevisor2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboRevisor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboRevisor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProyectoActionPerformed
        // TODO add your handling code here:
        if (cargandoProyectos) {
            return; // ← Bloquea si está inicializando
        }
        String nombreProyecto = (String) cboProyecto.getSelectedItem();
        if (nombreProyecto == null || nombreProyecto.trim().isEmpty()) {
            txtDescripcion.setText("");
            txtAlumnos.setText("");
            proyectoSeleccionado = null;
            return;
        }

        for (Proyecto p : controlProyecto.listarProyectos()) {
            if (p.getNombreProyecto().equals(nombreProyecto)) {
                proyectoSeleccionado = p;
                txtDescripcion.setText(p.getDescripcion());

                StringBuilder alumnos = new StringBuilder();
                for (Estudiante est : p.getEstudianteCollection()) {
                    Persona per = est.getIdPersona();
                    alumnos.append("Nombre: ").append(per.getNombre())
                            .append(" ").append(per.getApellidoP())
                            .append(" ").append(per.getApellidoM())
                            .append(" | No. Control: ").append(est.getNumControl()).append("\n");
                }
                txtAlumnos.setText(alumnos.toString());
                break;
            }
        }
    }//GEN-LAST:event_cboProyectoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
        if (proyectoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un proyecto primero.");
            return;
        }

        String asesor = (String) cboAsesor.getSelectedItem();
        String rev1 = (String) cboRevisor1.getSelectedItem();
        String rev2 = (String) cboRevisor2.getSelectedItem();

        if (asesor == null || rev1 == null || asesor.contains("Selecciona") || rev1.contains("Selecciona")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un asesor y un revisor.");
            return;
        }

        if (asesor.equals(rev1) || (rev2 != null && (asesor.equals(rev2) || rev1.equals(rev2)))) {
            JOptionPane.showMessageDialog(this, "No puede asignar el mismo docente en más de un rol.");
            return;
        }

        Docente docAsesor = buscarDocentePorNombre(asesor);
        Docente docRev1 = buscarDocentePorNombre(rev1);
        Docente docRev2 = (rev2 != null && !rev2.contains("Selecciona")) ? buscarDocentePorNombre(rev2) : null;

        // Validar duplicidad de rol
        if (docenteYaAsignado(proyectoSeleccionado, docAsesor) ||
            docenteYaAsignado(proyectoSeleccionado, docRev1) ||
            (docRev2 != null && docenteYaAsignado(proyectoSeleccionado, docRev2))) {
            JOptionPane.showMessageDialog(this, "Uno o más docentes ya están asignados al proyecto con otro rol.");
            return;
        }

        guardarRelacion(docAsesor, proyectoSeleccionado, "Asesor");
        guardarRelacion(docRev1, proyectoSeleccionado, "Revisor");
        if (docRev2 != null) {
            guardarRelacion(docRev2, proyectoSeleccionado, "Revisor");
        }

        JOptionPane.showMessageDialog(this, "Docentes asignados correctamente.");

        // Selección de fechas
        java.time.LocalDate hoy = java.time.LocalDate.now();
        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
        java.time.LocalDate[] fechas = {
            hoy, hoy.plusDays(1), hoy.plusDays(2), hoy.plusDays(3)
        };
        String[] opciones = new String[fechas.length];
        for (int i = 0; i < fechas.length; i++) {
            opciones[i] = fechas[i].format(formatter);
        }

        int seleccion = -1;
        while (seleccion < 0) {
            seleccion = JOptionPane.showOptionDialog(
                    this,
                    "Selecciona la fecha de inicio de residencia para este proyecto:",
                    "Establecer fecha de inicio",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    opciones,
                    opciones[0]);
        }

        java.util.Date dateInicio = java.util.Date.from(fechas[seleccion].atStartOfDay(java.time.ZoneId.systemDefault()).toInstant());
        java.util.Date dateFin = java.util.Date.from(fechas[seleccion].plusWeeks(18).atStartOfDay(java.time.ZoneId.systemDefault()).toInstant());

        Proyecto proyBD = controlProyecto.buscarProyectoPorId(proyectoSeleccionado.getIdProyecto());
        proyBD.setFechaInicio(dateInicio);
        proyBD.setFechaFin(dateFin);
        controlProyecto.editarProyecto(proyBD);

        // Refrescar tabla y cerrar
        JOptionPane.showMessageDialog(this, "Fechas guardadas correctamente.");
        limpiarFormulario();
        new BancoDeProyectos().cargarTablaProyectos();
        dispose();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if (!txtDescripcion.getText().isEmpty() || !txtAlumnos.getText().isEmpty()) {
            int opcion = JOptionPane.showConfirmDialog(null,
                    "Hay información cargada. ¿Seguro que desea cancelar?",
                    "Confirmación", JOptionPane.YES_NO_OPTION);
            if (opcion != JOptionPane.YES_OPTION) {
                return;
            }
        }
        limpiarFormulario();
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private Docente buscarDocentePorNombre(String nombreCompleto) {
        for (Docente d : controlDocente.listarDocentes()) {
            String nombre = d.getIdPersona().getNombre() + " "
                    + d.getIdPersona().getApellidoP() + " "
                    + d.getIdPersona().getApellidoM();
            if (nombre.equals(nombreCompleto)) {
                return d;
            }
        }
        return null;
    }

    private void guardarRelacion(Docente docente, Proyecto proyecto, String rol) throws Exception {
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("SigerproMVC");
    DocenteProyectoJpaController controlPD = new DocenteProyectoJpaController(emf);

    DocenteProyectoPK pk = new DocenteProyectoPK(proyecto.getIdProyecto(), docente.getNoTarjeta());
    DocenteProyecto existente = controlPD.findDocenteProyecto(pk);

    if (existente != null) {
        throw new Exception("El docente ya está asignado a este proyecto con otro rol: " + existente.getRolDocente());
    }

    DocenteProyecto pd = new DocenteProyecto();
    pd.setDocenteProyectoPK(pk);
    pd.setDocente(docente);
    pd.setProyecto(proyecto);
    pd.setRolDocente(rol);
    controlPD.create(pd);
}

    private void limpiarFormulario() {
        cboProyecto.setSelectedIndex(-1);
        cboAsesor.setSelectedIndex(-1);
        cboRevisor1.setSelectedIndex(-1);
        cboRevisor2.setSelectedIndex(-1);
        txtAlumnos.setText("");
        txtDescripcion.setText("");
        proyectoSeleccionado = null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProyectoRevAse().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboAsesor;
    private javax.swing.JComboBox<String> cboProyecto;
    private javax.swing.JComboBox<String> cboRevisor1;
    private javax.swing.JComboBox<String> cboRevisor2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAlumnos;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
